import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Leaflet Ts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-5 text-center">
        <h1 className="mb-3">Pishgaman Asia</h1>
        <p style={{ textAlign: "justify" }}>
          Dolor tempor pariatur sint laborum magna est duis minim irure
          cupidatat in veniam anim culpa. Esse nulla sit ea labore deserunt
          cupidatat nostrud eu tempor cillum non quis eu consectetur. Laborum
          anim cillum aliquip ut ullamco nisi consectetur. Do ut Lorem
          exercitation non ut excepteur sint tempor quis enim incididunt nostrud
          Lorem Lorem. Consectetur ipsum do aliqua elit ipsum duis sint laboris
          aliquip nostrud aute. Sint esse nisi incididunt sint laboris anim
          laboris. Enim eiusmod Lorem id magna irure aliqua nulla voluptate sint
          nostrud dolor mollit ipsum.
        </p>
      </div>
    </>
  );
};
export default HomePage;
